apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    tire: database
spec:
  selector:
    project: roboshop
    component: mongodb
    tire: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: roboshop
  lables:
    project: roboshop
    component: mongodb
    tire: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mongodb
      tire: database
  template:
    metadata:
      name: roboshop
      labels:
        project: roboshop
        component: mongodb
        tire: database
    spec:
      containers:
      - name: mongodb
        image: ramslella/mongodb:v2