apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
  labels: 
    project: roboshop
    environment: dev
    component: redis
    tire: database
spec:
  selector:
    project: roboshop
    component: redis
    environment: dev
    tire: database
  ports: 
  - protocol: TCP
    port: 6379
    targetPort: 6379
---
apiVersion: apps/v1
kind: Deploymnet
metadata: 
  name: redis
  namespace: roboshop
  labels:
    proect: roboshop
    component: redis
    environment: dev
    tire: database
spec:
  replicas: 1
  selector:
    matchLabels:
      proect: roboshop
      component: redis
      environment: dev
      tire: database
  template:
    metadata:
      name: redis
      namespace: roboshop
      labels:
        proect: roboshop
        component: redis
        environment: dev
        tire: database
    spec:
      containers:
      - name: redis
        image: redis:7.0