apiVersion: v1
kind: Service
metadata: 
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: rabbitmq
    tire: database
spec: 
  selector:
    project: roboshop
    environment: dev
    component: rabbitmq
    tire: database
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    project: roboshop
    environment: dev
    component: payment
    tire: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      environment: dev
      component: rabbitmq
      tire: database
template:
  metadata:
    name: payment
    namespace: roboshop
    labels:
      project: roboshop
      environment: dev
      component: rabbitmq
      tire: database
  spec:
    containers:
    - name: payment
      image: ramslella/payment:v2