apiVersion: v1
kind: Secret 
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    environment: dev
    tire: database
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQo="
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    environment: dev
    tire: database
spec:
  selector:
    project: roboshop
    component: mysql
    environment: dev
    tire: database
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels:
    project: roboshop
    component: mysql
    environment: dev
    tire: database
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: mysql
      environment: dev
      tire: database
  template:
    metadata:
      name: mysql
      namespace: roboshop
      labels:
        project: roboshop
        component: mysql
        environment: dev
        tire: database
    spec:
      containers:
      - name: mysql
        image: ramslella/mysql:v2
        envFrom:
        - secretRef:
            name: mysql
