apiVersion: v1
kind: ConfigMap
metadata: 
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
    tire: backend
data:
  REDIS_HOST: "redis" 
  CATALOGUE_HOST: "catalogue"
  CATALOGUE_PORT: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
    tire: backend
spec:
  selector:
    project: roboshop
    component: cart
    environment: dev
    tire: backend
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: roboshop
  labels:
    project: roboshop
    component: cart
    environment: dev
    tire: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      project: roboshop
      component: cart
      environment: dev
      tire: backend
  template:
    metadata:
      name: cart
      namespace: roboshop
      labels:
        project: roboshop
        component: cart
        environment: dev
        tire: backend
    spec:
      containers:
      - name: cart
        image: ramslella/cart:v2
        envFrom:
        - configMapRef:
            name: cart